<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-02-01 11:16

from django.conf import settings
=======
# Generated by Django 3.1.5 on 2021-02-12 16:54

>>>>>>> da19810a2703c7ded6b7ef8719755b5ed5210cc2
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> da19810a2703c7ded6b7ef8719755b5ed5210cc2
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('product_category', models.CharField(blank=True, max_length=30, null=True)),
                ('product_registration_date', models.DateField(blank=True, null=True)),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
>>>>>>> da19810a2703c7ded6b7ef8719755b5ed5210cc2
            ],
        ),
    ]
